Repository kubewarden/policy-sdk-go, pull requests merged in 2024-01, with the labels that each got.

#62 fix: wrong Kubernetes kinds.
  kubewarden.go
  kubewarden_test.go
Labels: kind/bug

#64 feat: make Go Wasi policies context aware
  pkg/capabilities/hostcaller_native.go
  pkg/capabilities/hostcaller_tinygo.go
  pkg/capabilities/hostcaller_wasip1.go
  protocol/protocol.go
Labels: kind/feature, kind/enhancement

#65 fix: make conformant k8s requests
  pkg/capabilities/kubernetes/kubernetes_test.go
  pkg/capabilities/kubernetes/types.go
Labels: kind/bug

#67 fix!: allow namespace to be nil in GetResourceRequest type
  pkg/capabilities/kubernetes/kubernetes_test.go
  pkg/capabilities/kubernetes/types.go
Labels: kind/bug, kind/breaking-change
