Repository kubewarden/policy-sdk-go, pull requests merged in 2024-06, with the labels that each got.

#85 chore: add Kubewarden repository badges.
  README.md
Labels: kind/chore

#88 fix: sigstore verification of GH action without repo
  pkg/capabilities/oci/verify_v2/types.go
  pkg/capabilities/oci/verify_v2/verify_v2_test.go
Labels: kind/bug

#90 feat: expose capability to get OCI image configuration.
  pkg/capabilities/oci/manifest_config/manifest.go
  pkg/capabilities/oci/manifest_config/manifest_test.go
  pkg/capabilities/oci/manifest_config/types.go
Labels: kind/feature

#91 fix: support changes done by TinyGo 0.32.0
  Makefile
  log_writer_native.go
  log_writer_tinygo.go
  pkg/capabilities/hostcaller_gc_wasip1.go
  pkg/capabilities/hostcaller_tinygo.go
  protocol/protocol.go
Labels: kind/bug, area/dependencies
